### PR TITLE
RXMask Registers Definition Correction

### PR DESCRIPTION
**Pull request by RowanTaubitz**
Small bug fix, had me stumped for a few hours, might help someone else in the future to have this corrected here. 
Thanks

### CODE REVIEW

**Comment by adamvoss** [comment]
Hi @RowanTaubitz.  Thank you for the PR!

I've recently gained the privileges to maintain this library and could merge this (don't worry about GitHub saying there is a merge conflict).  However, I don't know much about this library.  Could you tell me if there is a way I can verify your change is correct (datasheet reference, test code, etc.)?

**Comment by RowanTaubitz** [comment]
Hi @adamvoss , 

This took me back! You can verify it is correct by checking the datasheet. The datasheet for the part is available here http://www.microchip.com/wwwproducts/en/en010406

On page 37, register 4-14 describes RXMnSIDH and gives the addresses as 20h and 24h for mask 0 & 1 respectively. Just below that describes RXMnSIDL addresses, which are 21h and 25h. Before my changes the defines had the addresses for mask 0 the wrong way around, so it had RXM0SIDH as 0x21 instead of 0x20, and RXM0SIDL as 0x20 instead of 0x21.

**Comment by RowanTaubitz** [comment]
Sorry, I didn't mean to close this. How do I go about making the changes again?

**Comment by collin80** [comment]
You deleted your repo where the pull request was from. So, you'll have to recreate that repo, make the appropriate changes, and resubmit the pull request. Nobody can reopen this current one.

**Comment by adamvoss** [comment]
Unfortunately cannot give the merged status on GitHub, but it has now been merged.  Thanks!

**Pull request closed without merging**
